# Generated by Django 2.2 on 2019-04-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconfigruation', '0002_message_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='secondaryText',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
