# Generated by Django 2.2 on 2019-04-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messagesconfigruation', '0003_message_secondarytext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='secondaryText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
